name: vimedika
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.8
  easy_sidemenu: ^0.6.1
  flutter_launcher_icons: ^0.14.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  google_fonts: ^4.0.5
  lottie: ^3.3.1
  page_transition: ^2.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  websafe_svg: ^3.0.1+10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
